// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PPTT.Data;

#nullable disable

namespace PPTT.Migrations
{
    [DbContext(typeof(DBPPTTContext))]
    partial class DBPPTTContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PPTT.Models.Admin", b =>
                {
                    b.Property<int>("ID_Usuario_Pk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Usuario_Pk"));

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DNI")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Fecha_Alta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Fecha_Baja")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ID_Division_Fk")
                        .HasColumnType("int");

                    b.Property<int?>("ID_Password_Fk")
                        .HasColumnType("int");

                    b.Property<int?>("ID_Rol_Fk")
                        .HasColumnType("int");

                    b.Property<int?>("ID_Servicio_Fk")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero_Control")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Usuario_Pk");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("PPTT.Models.DependenciaInterna", b =>
                {
                    b.Property<int>("ID_Dependencia_Interna_PK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Dependencia_Interna_PK"));

                    b.Property<string>("Descripcion_Dependencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ID_Organismo_FK")
                        .HasColumnType("int");

                    b.HasKey("ID_Dependencia_Interna_PK");

                    b.ToTable("DependenciaInterna");
                });

            modelBuilder.Entity("PPTT.Models.Division", b =>
                {
                    b.Property<int>("ID_Division_Pk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Division_Pk"));

                    b.Property<string>("Descripcion_Division")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Division_Pk");

                    b.ToTable("Divisions");
                });

            modelBuilder.Entity("PPTT.Models.Estado", b =>
                {
                    b.Property<int>("ID_Estado_PK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Estado_PK"));

                    b.Property<string>("Descripcion_Estado")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Estado_PK");

                    b.ToTable("Estado");
                });

            modelBuilder.Entity("PPTT.Models.Grado", b =>
                {
                    b.Property<int>("ID_Grado_PK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Grado_PK"));

                    b.Property<string>("Descripcion_Grado")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Grado_PK");

                    b.ToTable("grado");
                });

            modelBuilder.Entity("PPTT.Models.Organismo", b =>
                {
                    b.Property<int>("ID_Organismo_PK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Organismo_PK"));

                    b.Property<string>("Descripcion_organismo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Organismo_PK");

                    b.ToTable("Organismo");
                });

            modelBuilder.Entity("PPTT.Models.PTUsuario", b =>
                {
                    b.Property<int>("ID_Orden_Trabajo_Pk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Orden_Trabajo_Pk"));

                    b.Property<string>("Apellido_Solicitante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color_Oficina_PT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color_Oficina_Solicitante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DNI_Solicitante")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha_Estimada_Fin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fecha_Inicio_Suspendido")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fecha_Subida")
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_Dependencia_Interna_Fk")
                        .HasColumnType("int");

                    b.Property<int>("ID_Estado_Fk")
                        .HasColumnType("int");

                    b.Property<int>("ID_Grado_Fk")
                        .HasColumnType("int");

                    b.Property<int>("ID_Organismo_Fk")
                        .HasColumnType("int");

                    b.Property<string>("IP_Solicitante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre_Solicitante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero_Control_Solicitante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero_Oficina_PT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero_Oficina_Solicitante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Piso_Oficina_PT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Piso_Oficina_Solicitante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Prioridad")
                        .HasColumnType("int");

                    b.Property<string>("RTI_Solicitante")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Orden_Trabajo_Pk");

                    b.ToTable("orden_de_trabajo_usuario");
                });

            modelBuilder.Entity("PPTT.Models.Prueba", b =>
                {
                    b.Property<int?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("ID"));

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Prueba");
                });

            modelBuilder.Entity("PPTT.Models.Servicio", b =>
                {
                    b.Property<int>("ID_Servicio_Pk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Servicio_Pk"));

                    b.Property<string>("Descripcion_Servicio")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Servicio_Pk");

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("PPTT.Models.Tarea", b =>
                {
                    b.Property<int>("Id_Tarea_Pk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Tarea_Pk"));

                    b.Property<string>("Descripcion_Tarea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Id_Servicio_Fk")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Tarea_Pk");

                    b.ToTable("Tarea");
                });
#pragma warning restore 612, 618
        }
    }
}
